# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir O:/ADI_Internship/Assignments/FFT_Final_Project/FFT_8_Point_Radix_2_FPGA/FFT_8_Point_Radix_2_FPGA.cache/wt [current_project]
set_property parent.project_path O:/ADI_Internship/Assignments/FFT_Final_Project/FFT_8_Point_Radix_2_FPGA/FFT_8_Point_Radix_2_FPGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo o:/ADI_Internship/Assignments/FFT_Final_Project/FFT_8_Point_Radix_2_FPGA/FFT_8_Point_Radix_2_FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  O:/ADI_Internship/Assignments/FFT_Final_Project/ASIC_Backend/Design_Files/Complex_Add_Sub.sv
  O:/ADI_Internship/Assignments/FFT_Final_Project/ASIC_Backend/Design_Files/Complex_Multi.sv
  O:/ADI_Internship/Assignments/FFT_Final_Project/ASIC_Backend/Design_Files/Dn_Counter.sv
  O:/ADI_Internship/Assignments/FFT_Final_Project/ASIC_Backend/Design_Files/FFT_8_Point_Radix_2_TOP.sv
  O:/ADI_Internship/Assignments/FFT_Final_Project/ASIC_Backend/Design_Files/MAC_Unit.sv
  O:/ADI_Internship/Assignments/FFT_Final_Project/ASIC_Backend/Design_Files/Single_Stage_FFT_8_2.sv
  O:/ADI_Internship/Assignments/FFT_Final_Project/ASIC_Backend/Design_Files/Twiddle_LUT.sv
  O:/ADI_Internship/Assignments/FFT_Final_Project/ASIC_Backend/Design_Files/FFT_8_Point_Radix_2_Wrapper.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc O:/ADI_Internship/Assignments/FFT_Final_Project/FFT_8_Point_Radix_2_FPGA/FFT_8_Point_Radix_2_FPGA.srcs/constrs_1/new/constrs.xdc
set_property used_in_implementation false [get_files O:/ADI_Internship/Assignments/FFT_Final_Project/FFT_8_Point_Radix_2_FPGA/FFT_8_Point_Radix_2_FPGA.srcs/constrs_1/new/constrs.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top FFT_8_Point_Radix_2_Wrapper -part xc7z020clg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FFT_8_Point_Radix_2_Wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FFT_8_Point_Radix_2_Wrapper_utilization_synth.rpt -pb FFT_8_Point_Radix_2_Wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
