onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/IN0_Img
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/IN0_Real
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/IN1_Img
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/IN1_Real
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Multi_OUT_Img
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Multi_OUT_Real
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/OUT0_Img
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/OUT0_Real
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/OUT1_Img
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/OUT1_Real
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/W8_Img
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/W8_Index
add wave -noupdate -expand -group 1_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/W8_Real
add wave -noupdate -expand -group 1_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Cplx_Multiplier/IN0_Img
add wave -noupdate -expand -group 1_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Cplx_Multiplier/IN0_Real
add wave -noupdate -expand -group 1_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Cplx_Multiplier/IN1_Img
add wave -noupdate -expand -group 1_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Cplx_Multiplier/IN1_Real
add wave -noupdate -expand -group 1_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Cplx_Multiplier/OUT_Img
add wave -noupdate -expand -group 1_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Cplx_Multiplier/OUT_Real
add wave -noupdate -expand -group 1_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Cplx_Multiplier/Product_Img_Final
add wave -noupdate -expand -group 1_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Cplx_Multiplier/Product_Img_Part_1
add wave -noupdate -expand -group 1_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Cplx_Multiplier/Product_Img_Part_2
add wave -noupdate -expand -group 1_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Cplx_Multiplier/Product_Real_Final
add wave -noupdate -expand -group 1_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Cplx_Multiplier/Product_Real_Part_1
add wave -noupdate -expand -group 1_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_0/Cplx_Multiplier/Product_Real_Part_2
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/IN0_Img
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/IN0_Real
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/IN1_Img
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/IN1_Real
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Multi_OUT_Img
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Multi_OUT_Real
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/OUT0_Img
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/OUT0_Real
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/OUT1_Img
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/OUT1_Real
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/W8_Img
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/W8_Index
add wave -noupdate -expand -group 1_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/W8_Real
add wave -noupdate -expand -group 1_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Cplx_Multiplier/IN0_Img
add wave -noupdate -expand -group 1_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Cplx_Multiplier/IN0_Real
add wave -noupdate -expand -group 1_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Cplx_Multiplier/IN1_Img
add wave -noupdate -expand -group 1_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Cplx_Multiplier/IN1_Real
add wave -noupdate -expand -group 1_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Cplx_Multiplier/OUT_Img
add wave -noupdate -expand -group 1_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Cplx_Multiplier/OUT_Real
add wave -noupdate -expand -group 1_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Cplx_Multiplier/Product_Img_Final
add wave -noupdate -expand -group 1_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Cplx_Multiplier/Product_Img_Part_1
add wave -noupdate -expand -group 1_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Cplx_Multiplier/Product_Img_Part_2
add wave -noupdate -expand -group 1_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Cplx_Multiplier/Product_Real_Final
add wave -noupdate -expand -group 1_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Cplx_Multiplier/Product_Real_Part_1
add wave -noupdate -expand -group 1_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_1/Cplx_Multiplier/Product_Real_Part_2
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/IN0_Img
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/IN0_Real
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/IN1_Img
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/IN1_Real
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Multi_OUT_Img
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Multi_OUT_Real
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/OUT0_Img
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/OUT0_Real
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/OUT1_Img
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/OUT1_Real
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/W8_Img
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/W8_Index
add wave -noupdate -expand -group 1_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/W8_Real
add wave -noupdate -expand -group 1_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Cplx_Multiplier/IN0_Img
add wave -noupdate -expand -group 1_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Cplx_Multiplier/IN0_Real
add wave -noupdate -expand -group 1_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Cplx_Multiplier/IN1_Img
add wave -noupdate -expand -group 1_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Cplx_Multiplier/IN1_Real
add wave -noupdate -expand -group 1_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Cplx_Multiplier/OUT_Img
add wave -noupdate -expand -group 1_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Cplx_Multiplier/OUT_Real
add wave -noupdate -expand -group 1_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Cplx_Multiplier/Product_Img_Final
add wave -noupdate -expand -group 1_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Cplx_Multiplier/Product_Img_Part_1
add wave -noupdate -expand -group 1_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Cplx_Multiplier/Product_Img_Part_2
add wave -noupdate -expand -group 1_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Cplx_Multiplier/Product_Real_Final
add wave -noupdate -expand -group 1_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Cplx_Multiplier/Product_Real_Part_1
add wave -noupdate -expand -group 1_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_2/Cplx_Multiplier/Product_Real_Part_2
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/IN0_Img
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/IN0_Real
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/IN1_Img
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/IN1_Real
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Multi_OUT_Img
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Multi_OUT_Real
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/OUT0_Img
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/OUT0_Real
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/OUT1_Img
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/OUT1_Real
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/W8_Img
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/W8_Index
add wave -noupdate -expand -group 1_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/W8_Real
add wave -noupdate -expand -group 1_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Cplx_Multiplier/IN0_Img
add wave -noupdate -expand -group 1_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Cplx_Multiplier/IN0_Real
add wave -noupdate -expand -group 1_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Cplx_Multiplier/IN1_Img
add wave -noupdate -expand -group 1_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Cplx_Multiplier/IN1_Real
add wave -noupdate -expand -group 1_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Cplx_Multiplier/OUT_Img
add wave -noupdate -expand -group 1_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Cplx_Multiplier/OUT_Real
add wave -noupdate -expand -group 1_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Cplx_Multiplier/Product_Img_Final
add wave -noupdate -expand -group 1_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Cplx_Multiplier/Product_Img_Part_1
add wave -noupdate -expand -group 1_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Cplx_Multiplier/Product_Img_Part_2
add wave -noupdate -expand -group 1_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Cplx_Multiplier/Product_Real_Final
add wave -noupdate -expand -group 1_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Cplx_Multiplier/Product_Real_Part_1
add wave -noupdate -expand -group 1_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/First_Stage/MAC_3/Cplx_Multiplier/Product_Real_Part_2

add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/IN0_Img
add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/IN0_Real
add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/IN1_Img
add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/IN1_Real
add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Multi_OUT_Img
add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Multi_OUT_Real
add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/OUT0_Img
add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/OUT0_Real
add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/OUT1_Img
add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/OUT1_Real
add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/W8_Img
add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/W8_Index
add wave -noupdate -expand -group 2_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/W8_Real
add wave -noupdate -expand -group 2_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Cplx_Multiplier/IN0_Img
add wave -noupdate -expand -group 2_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Cplx_Multiplier/IN0_Real
add wave -noupdate -expand -group 2_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Cplx_Multiplier/IN1_Img
add wave -noupdate -expand -group 2_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Cplx_Multiplier/IN1_Real
add wave -noupdate -expand -group 2_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Cplx_Multiplier/OUT_Img
add wave -noupdate -expand -group 2_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Cplx_Multiplier/OUT_Real
add wave -noupdate -expand -group 2_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Cplx_Multiplier/Product_Img_Final
add wave -noupdate -expand -group 2_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Cplx_Multiplier/Product_Img_Part_1
add wave -noupdate -expand -group 2_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Cplx_Multiplier/Product_Img_Part_2
add wave -noupdate -expand -group 2_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Cplx_Multiplier/Product_Real_Final
add wave -noupdate -expand -group 2_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Cplx_Multiplier/Product_Real_Part_1
add wave -noupdate -expand -group 2_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_0/Cplx_Multiplier/Product_Real_Part_2
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/IN0_Img
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/IN0_Real
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/IN1_Img
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/IN1_Real
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Multi_OUT_Img
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Multi_OUT_Real
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/OUT0_Img
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/OUT0_Real
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/OUT1_Img
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/OUT1_Real
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/W8_Img
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/W8_Index
add wave -noupdate -expand -group 2_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/W8_Real
add wave -noupdate -expand -group 2_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Cplx_Multiplier/IN0_Img
add wave -noupdate -expand -group 2_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Cplx_Multiplier/IN0_Real
add wave -noupdate -expand -group 2_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Cplx_Multiplier/IN1_Img
add wave -noupdate -expand -group 2_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Cplx_Multiplier/IN1_Real
add wave -noupdate -expand -group 2_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Cplx_Multiplier/OUT_Img
add wave -noupdate -expand -group 2_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Cplx_Multiplier/OUT_Real
add wave -noupdate -expand -group 2_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Cplx_Multiplier/Product_Img_Final
add wave -noupdate -expand -group 2_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Cplx_Multiplier/Product_Img_Part_1
add wave -noupdate -expand -group 2_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Cplx_Multiplier/Product_Img_Part_2
add wave -noupdate -expand -group 2_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Cplx_Multiplier/Product_Real_Final
add wave -noupdate -expand -group 2_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Cplx_Multiplier/Product_Real_Part_1
add wave -noupdate -expand -group 2_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_1/Cplx_Multiplier/Product_Real_Part_2
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/IN0_Img
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/IN0_Real
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/IN1_Img
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/IN1_Real
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Multi_OUT_Img
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Multi_OUT_Real
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/OUT0_Img
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/OUT0_Real
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/OUT1_Img
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/OUT1_Real
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/W8_Img
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/W8_Index
add wave -noupdate -expand -group 2_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/W8_Real
add wave -noupdate -expand -group 2_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Cplx_Multiplier/IN0_Img
add wave -noupdate -expand -group 2_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Cplx_Multiplier/IN0_Real
add wave -noupdate -expand -group 2_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Cplx_Multiplier/IN1_Img
add wave -noupdate -expand -group 2_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Cplx_Multiplier/IN1_Real
add wave -noupdate -expand -group 2_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Cplx_Multiplier/OUT_Img
add wave -noupdate -expand -group 2_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Cplx_Multiplier/OUT_Real
add wave -noupdate -expand -group 2_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Cplx_Multiplier/Product_Img_Final
add wave -noupdate -expand -group 2_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Cplx_Multiplier/Product_Img_Part_1
add wave -noupdate -expand -group 2_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Cplx_Multiplier/Product_Img_Part_2
add wave -noupdate -expand -group 2_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Cplx_Multiplier/Product_Real_Final
add wave -noupdate -expand -group 2_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Cplx_Multiplier/Product_Real_Part_1
add wave -noupdate -expand -group 2_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_2/Cplx_Multiplier/Product_Real_Part_2
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/IN0_Img
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/IN0_Real
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/IN1_Img
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/IN1_Real
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Multi_OUT_Img
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Multi_OUT_Real
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/OUT0_Img
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/OUT0_Real
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/OUT1_Img
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/OUT1_Real
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/W8_Img
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/W8_Index
add wave -noupdate -expand -group 2_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/W8_Real
add wave -noupdate -expand -group 2_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Cplx_Multiplier/IN0_Img
add wave -noupdate -expand -group 2_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Cplx_Multiplier/IN0_Real
add wave -noupdate -expand -group 2_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Cplx_Multiplier/IN1_Img
add wave -noupdate -expand -group 2_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Cplx_Multiplier/IN1_Real
add wave -noupdate -expand -group 2_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Cplx_Multiplier/OUT_Img
add wave -noupdate -expand -group 2_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Cplx_Multiplier/OUT_Real
add wave -noupdate -expand -group 2_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Cplx_Multiplier/Product_Img_Final
add wave -noupdate -expand -group 2_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Cplx_Multiplier/Product_Img_Part_1
add wave -noupdate -expand -group 2_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Cplx_Multiplier/Product_Img_Part_2
add wave -noupdate -expand -group 2_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Cplx_Multiplier/Product_Real_Final
add wave -noupdate -expand -group 2_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Cplx_Multiplier/Product_Real_Part_1
add wave -noupdate -expand -group 2_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Second_Stage/MAC_3/Cplx_Multiplier/Product_Real_Part_2

add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/IN0_Img
add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/IN0_Real
add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/IN1_Img
add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/IN1_Real
add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Multi_OUT_Img
add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Multi_OUT_Real
add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/OUT0_Img
add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/OUT0_Real
add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/OUT1_Img
add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/OUT1_Real
add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/W8_Img
add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/W8_Index
add wave -noupdate -expand -group 3_MAC0 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/W8_Real
add wave -noupdate -expand -group 3_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Cplx_Multiplier/IN0_Img
add wave -noupdate -expand -group 3_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Cplx_Multiplier/IN0_Real
add wave -noupdate -expand -group 3_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Cplx_Multiplier/IN1_Img
add wave -noupdate -expand -group 3_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Cplx_Multiplier/IN1_Real
add wave -noupdate -expand -group 3_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Cplx_Multiplier/OUT_Img
add wave -noupdate -expand -group 3_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Cplx_Multiplier/OUT_Real
add wave -noupdate -expand -group 3_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Cplx_Multiplier/Product_Img_Final
add wave -noupdate -expand -group 3_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Cplx_Multiplier/Product_Img_Part_1
add wave -noupdate -expand -group 3_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Cplx_Multiplier/Product_Img_Part_2
add wave -noupdate -expand -group 3_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Cplx_Multiplier/Product_Real_Final
add wave -noupdate -expand -group 3_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Cplx_Multiplier/Product_Real_Part_1
add wave -noupdate -expand -group 3_MAC0_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_0/Cplx_Multiplier/Product_Real_Part_2
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/IN0_Img
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/IN0_Real
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/IN1_Img
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/IN1_Real
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Multi_OUT_Img
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Multi_OUT_Real
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/OUT0_Img
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/OUT0_Real
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/OUT1_Img
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/OUT1_Real
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/W8_Img
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/W8_Index
add wave -noupdate -expand -group 3_MAC1 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/W8_Real
add wave -noupdate -expand -group 3_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Cplx_Multiplier/IN0_Img
add wave -noupdate -expand -group 3_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Cplx_Multiplier/IN0_Real
add wave -noupdate -expand -group 3_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Cplx_Multiplier/IN1_Img
add wave -noupdate -expand -group 3_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Cplx_Multiplier/IN1_Real
add wave -noupdate -expand -group 3_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Cplx_Multiplier/OUT_Img
add wave -noupdate -expand -group 3_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Cplx_Multiplier/OUT_Real
add wave -noupdate -expand -group 3_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Cplx_Multiplier/Product_Img_Final
add wave -noupdate -expand -group 3_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Cplx_Multiplier/Product_Img_Part_1
add wave -noupdate -expand -group 3_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Cplx_Multiplier/Product_Img_Part_2
add wave -noupdate -expand -group 3_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Cplx_Multiplier/Product_Real_Final
add wave -noupdate -expand -group 3_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Cplx_Multiplier/Product_Real_Part_1
add wave -noupdate -expand -group 3_MAC1_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_1/Cplx_Multiplier/Product_Real_Part_2
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/IN0_Img
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/IN0_Real
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/IN1_Img
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/IN1_Real
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Multi_OUT_Img
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Multi_OUT_Real
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/OUT0_Img
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/OUT0_Real
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/OUT1_Img
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/OUT1_Real
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/W8_Img
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/W8_Index
add wave -noupdate -expand -group 3_MAC2 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/W8_Real
add wave -noupdate -expand -group 3_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Cplx_Multiplier/IN0_Img
add wave -noupdate -expand -group 3_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Cplx_Multiplier/IN0_Real
add wave -noupdate -expand -group 3_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Cplx_Multiplier/IN1_Img
add wave -noupdate -expand -group 3_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Cplx_Multiplier/IN1_Real
add wave -noupdate -expand -group 3_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Cplx_Multiplier/OUT_Img
add wave -noupdate -expand -group 3_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Cplx_Multiplier/OUT_Real
add wave -noupdate -expand -group 3_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Cplx_Multiplier/Product_Img_Final
add wave -noupdate -expand -group 3_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Cplx_Multiplier/Product_Img_Part_1
add wave -noupdate -expand -group 3_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Cplx_Multiplier/Product_Img_Part_2
add wave -noupdate -expand -group 3_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Cplx_Multiplier/Product_Real_Final
add wave -noupdate -expand -group 3_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Cplx_Multiplier/Product_Real_Part_1
add wave -noupdate -expand -group 3_MAC2_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_2/Cplx_Multiplier/Product_Real_Part_2
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/IN0_Img
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/IN0_Real
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/IN1_Img
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/IN1_Real
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Multi_OUT_Img
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Multi_OUT_Real
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/OUT0_Img
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/OUT0_Real
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/OUT1_Img
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/OUT1_Real
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/W8_Img
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/W8_Index
add wave -noupdate -expand -group 3_MAC3 /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/W8_Real
add wave -noupdate -expand -group 3_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Cplx_Multiplier/IN0_Img
add wave -noupdate -expand -group 3_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Cplx_Multiplier/IN0_Real
add wave -noupdate -expand -group 3_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Cplx_Multiplier/IN1_Img
add wave -noupdate -expand -group 3_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Cplx_Multiplier/IN1_Real
add wave -noupdate -expand -group 3_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Cplx_Multiplier/OUT_Img
add wave -noupdate -expand -group 3_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Cplx_Multiplier/OUT_Real
add wave -noupdate -expand -group 3_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Cplx_Multiplier/Product_Img_Final
add wave -noupdate -expand -group 3_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Cplx_Multiplier/Product_Img_Part_1
add wave -noupdate -expand -group 3_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Cplx_Multiplier/Product_Img_Part_2
add wave -noupdate -expand -group 3_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Cplx_Multiplier/Product_Real_Final
add wave -noupdate -expand -group 3_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Cplx_Multiplier/Product_Real_Part_1
add wave -noupdate -expand -group 3_MAC3_Multi /FFT_8_Point_Radix_2_tb/FFT_8_Point_Radix_2_DUT/Third_Stage/MAC_3/Cplx_Multiplier/Product_Real_Part_2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1 ns}
